version: '2'

services:
  judge_server:
      image: noj
      restart: always
      read_only: true
      cap_drop:
          - SETPCAP
          - MKNOD
          - NET_BIND_SERVICE
          - SYS_CHROOT
          - SETFCAP
          - FSETID
      tmpfs:
          - /tmp
            #- /log
          - /judger:exec
      volumes:
            #- /var/www/NOJ/storage/test_case:/test_case:ro
            #- /var/www/NOJ/storage/log:/log
            #- /var/www/NOJ/storage/run:/judger
          - type: bind
            source: /var/www/NOJ/storage/test_case
            target: /test_case
            read_only: true
          - type: bind
            source: /var/www/NOJ/storage/logs
            target: /log
      environment:
          - BACKEND_URL=http://localhost/api/judge_server_heartbeat
          - SERVICE_URL=http://localhost:8080
          - TOKEN=base64:goeYHA5MLTAoI6+D8xwKhLfaiizI4lsEZsYWDPO4qBg=
      network_mode: "host"
